# Github actions for CI and CD workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ionic Angular and Python application
env:
  heroku_api_key: "1db8994c-c812-40a0-98e1-5bc5b8c83d5f"
  heroku_app_name: "ionic-grupo25"
  heroku_email: "j.morenot@uniandes.edu.co"

on:
  push:
    branches: [ feature/** ]
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ develop, release, main ]

jobs:
  deploy-backend-python:
    name: CI-Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Flask to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ env.heroku_api_key }}
        heroku_app_name: ${{ env.heroku_app_name }}
        heroku_email: ${{ env.heroku_email }}
        usedocker: true
        appdir: flaskr

  deploy-frontend-angular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Nginx to serve angular to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ env.heroku_api_key }}
        heroku_app_name: ${{ env.heroku_app_name }}
        heroku_email: ${{ env.heroku_email }}
        usedocker: true
        appdir: front-end/tutorial-canciones
        docker_build_args: |
          ENV_TYPE
      env:
          ENV_TYPE: production



